version: "3.2"

services:
  handler:
    build:
      context: .
      dockerfile: dockerfile-handler
    container_name: audit-flow-handler
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_HOST=mongodb
    ports:
      - "8003:8003"
    networks:
      - rabbit-server_rabbitmq_go_net
    restart: always

networks:
  rabbit-server_rabbitmq_go_net:
    external: true
