version: "3.2"

services:
  handler:
    build:
      context: .
      dockerfile: dockerfile-handler
    container_name: audit-flow-handler
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - MONGODB_HOST=mongodb
    ports:
      - "8003:8003"
    networks:
      - rabbitmq_go_net
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    restart: always

networks:
  rabbitmq_go_net:
    driver: bridge
